version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "0.0.0.0:3002:3002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3003:80"
    depends_on:
      - backend
    restart: unless-stopped
